### ISSUE TITLE
제품을 좀 더 다양한 조건을 가지고 검색한다.

### ISSUE THREAD

**Issue by KEEMSY** [KEEMSY/shoes-ordering-system#4]
### 설명

기존 시스템 분석에서 식별한 기능이었던 상품 검색 및 필터링의 대한 개발로, 제품카테고리(ProductCategory)를 통한 검색 기능을 개발했으나,  더 다양한 Product의 속성이 존재하며, 해당 속성들을 활용한 검색 기능을 개발한다.

> Product 클래스의 일부분: Product 클래스의 속성
```java
public class Product extends AggregateRoot<ProductId> {

    private final String name;
    private final ProductCategory productCategory;
    private final String description;
    private final Money price;

```
<br>

`name`, `price`, `productCategory` 속성들을 필터링 할 수 있는 기능을 개발하여, 기존의 제품카테고리(ProductCategory)를 통한 검색 기능을 고도화 한다.

- 신규 기능을 통해 좀 더 세분화된 제품 검색을 제공할 수 있다.

<br>

### 예상 작업량

- 다양한 Product 의 속성을 활용한 기능 개발에 대하여 각각 메서드를 따로 만드는 것이 아닌 `Querydsl` 을 활용하여 동적쿼리로 개발한다.
- DTO: `InputModel` 을 새로 생성하고, `outputModel` 은 기존의 `ProductQueryListResponse` 를 활용한다.
- 예상 작업기간 4일

> Adapter-DataAccess 계층

- [x] ProductQuerydslRepository 내 메서드 추가
- [x] ProductPersistanceAdapter 내 유스케이스 추가

<br>

> Domain-Application 계층

- [x] DTO 개발 및 테스트
- [x] ProductRepository 내 유스케이스 추가
- [x] ProductQueryService 내 메서드 추가
- [x] ProductListQueryHandler 내 메서드 추가

**Comment by triumph1** [comment]
elastic search 공부해 보시는 건?

**Comment by KEEMSY** [comment]
> elastic search 공부해 보시는 건?

elastic search 를 담당했던 레거시에서 사용해보고자 했다가 이유를 듣지 못하고 당차게 까이고 찾아본 기억으로 전체 텍스트 분석이나 로그 분석 할 때 사용한다 정도로만 알고있습니다..!

elastic search 가 지금 기능(혹은 이후의 확장을 고려한다면) 더 나은 선택 될 수 있을까요?! 혹은 관련해서 참고하면 좋을 자료가 있을까요!?

@triumph1

**Comment by triumph1** [comment]
으악 ㅋㅋㅋㅋㅋㅋㅋㅋㅌㅋ

**Comment by triumph1** [comment]
그럼여 디비에서 검색하면 인덱스 못 태우는데

문자열로 검색하는 기능은 디비가 아니라 검색엔진 써야죠

**Comment by triumph1** [comment]
근데 저도 제대로 파본적이 없어서
Udemy  강의 몇번 들어본게 다에여

**Comment by KEEMSY** [comment]
@triumph1 

생각해보니... 이름을 검색한다는 것은 특정 문자가 포함된 경우를 완전 탐색할테니... 이 부분도 고민을 해봐야겠네용..

(아 블랙홀 Udemy 다시 열어야하나..)
